# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Phase - install - `date`
  pre_build:
    commands:
      - echo Phase - pre_build - `date`
      - npm install
      - git clone https://63552f0ce7b8c5a771cb62a7977a2326802c9d8a@github.com/frkandris/gravitris-env.git
      - cp ./gravitris-env/env.production.json ./env.production.json
  build:
    commands:
      - echo Phase - build - `date`
  post_build:
    commands:
      - echo Phase - post_build - `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - server.js
    - package.json
    - client/includes/*
    - client/*
    - node_modules/*
    - public/stylesheets/*
    - public/*
    - routes/*
    - views/*
    - bin/*